const data = {
    products: [
       {
           _id:'1',
           name:'Gravity ',
           category:'wine',
           images:'/images/p-3.jpg',
           price:'130.00',
           countInStock:0,
           brand:'wine',
           rating:'4.5',
           numReviews:10,
           descriptions:'Alta Calidad',  
       },
       {
        _id:'2',
        name:'Gravity Falls',
        category:'wine',
        images:'/images/p-4.jpg',
        price:'140.00',
        countInStock:11,
        brand:'wine',
        rating:'4.5',
        numReviews:10,
        descriptions:'Alta Calidad',   
    },
    
    {
        _id:'3',
        name:'Falls',
        category:'wine',
        images:'/images/p-3.jpg',
        price:'150.00',
        countInStock:14,
        brand:'wine',
        rating:'4.5',
        numReviews:10,
        descriptions:'Alta Calidad',   
    },
    
    {
        _id:'4',
        name:'GravFalls',
        category:'wine',
        images:'/images/p-3.jpg',
        price:'160.00',
        countInStock:0,
        brand:'wine',
        rating:'4.5',
        numReviews:10,
        descriptions:'Alta Calidad',   
    },
    
    {
        _id:'5',
        name:'GravityFalls',
        category:'wine',
        images:'/images/p-3.jpg',
        price:'170.00',
        countInStock:14,
        brand:'wine',
        rating:'4.5',
        numReviews:10,
        descriptions:'Alta Calidad',   
    },
    {
        _id:'6',
        name:'Gravity F',
        category:'wine',
        images:'/images/p-3.jpg',
        price:'180.00',
        countInStock:15,
        brand:'wine',
        rating:'4.5',
        numReviews:10,
        descriptions:'Alta Calidad',   
    },
    
    ],
};

export default data;